language: ruby

os:
  - linux

arch:
  - amd64

before_install:
  - cd $HOME

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_extended_0.64.1_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.64.1_Linux-64bit.deb
  - gem install asciidoctor

before_script:
  - cd $TRAVIS_BUILD_DIR

script:
  - hugo
  
before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master