language: ruby

os:
  - linux

arch:
  - amd64

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_extended_0.64.1_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.64.1_Linux-64bit.deb
  - gem install asciidoctor

script:
  - hugo

before_deploy:
  - rm hugo_extended_0.64.1_Linux-64bit.deb

deploy:
  - provider: script
    script: ./deploy.sh
    cleanup: false
    on:
      branch: master