language: shell

os:
  - linux

arch:
  - amd64
  
git:
  depth: false

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_extended_0.64.1_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.64.1_Linux-64bit.deb

script:
  - hugo

deploy:
  - provider: script
    script: ./deploy.sh
    cleanup: false
    on:
      branch: master